s/\<CAUSE\>/RRCONF/g

diff --git a/replay b/replay
--- a/replay
+++ b/replay
@@ -9,19 +9,19 @@ export PATH=/sbin:/usr/sbin:/bin:/usr/bin
 test -r /etc/rrconf/rrconf.conf && source /etc/rrconf/rrconf.conf
 test -r ~/.rrconf.conf && source ~/.rrconf.conf
 
-export CAUSE=${CAUSE:=/opt/rrconf}
+export RRCONF=${RRCONF:=/opt/rrconf}
 
-test -r "${CAUSE}/lib.sh" || {
-  echo "Check if configuration or installation directory is present in \$CAUSE."
-  echo "I cannot read file ${CAUSE}/lib.sh file."
+test -r "${RRCONF}/lib.sh" || {
+  echo "Check if configuration or installation directory is present in \$RRCONF."
+  echo "I cannot read file ${RRCONF}/lib.sh file."
   exit 1
 }
 
 needname=1
-export CAUSEINC="${CAUSE}/lib.sh"
+export CAUSEINC="${RRCONF}/lib.sh"
 
 # include all functions and command line variable checks
-source "${CAUSE}/lib.sh"
+source "${RRCONF}/lib.sh"
 
 ## end of prologue
 _replay $*
